package com.fidelidad.programa.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * País. Nivel más alto de la jerarquía geográfica: País → Departamento → Ciudad.
 *
 * <p>Alimenta el desplegable "país" del formulario de inscripción.
 */
@Entity
@Table(
        name = "pais",
        uniqueConstraints = @UniqueConstraint(name = "uk_pais_nombre", columnNames = "nombre")
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Pais {

    /**
     * IDENTITY delega la generación del id a PostgreSQL, que crea la columna como
     * {@code bigint generated by default as identity}.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "nombre", nullable = false, length = 100)
    private String nombre;
}
