-- ===========================================================================
-- Programa de Fidelidad - Volcado de la base de datos
--
-- Contiene:
--   * La estructura completa: 6 tablas, claves primarias y foraneas, y las
--     restricciones de unicidad (entre ellas uk_cliente_identificacion_marca).
--   * Los datos semilla de los catalogos: 1 pais, 32 departamentos, 76 ciudades,
--     5 tipos de identificacion y las 6 marcas del programa.
--   * La tabla cliente vacia: se genero con --exclude-table-data=cliente, porque
--     los clientes son datos de prueba y no forman parte de la semilla.
--
-- Como cargarlo en una base limpia:
--   createdb -U postgres fidelidad_db
--   psql -U postgres -d fidelidad_db -f database/dump.sql
--
-- Notas:
--   * Generado con pg_dump --no-owner --no-privileges, para que se pueda cargar
--     con cualquier usuario y no solo con el que lo creo.
--   * Incluye --clean --if-exists, asi que se puede ejecutar mas de una vez sobre
--     la misma base sin errores.
--   * Se eliminaron las dos lineas de metacomandos que agrega pg_dump 18
--     (restrict / unrestrict): solo las entiende psql 18 y hacian fallar la carga
--     en versiones anteriores de psql.
-- ===========================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.departamento DROP CONSTRAINT IF EXISTS fk_departamento_pais;
ALTER TABLE IF EXISTS ONLY public.cliente DROP CONSTRAINT IF EXISTS fk_cliente_tipo_identificacion;
ALTER TABLE IF EXISTS ONLY public.cliente DROP CONSTRAINT IF EXISTS fk_cliente_marca;
ALTER TABLE IF EXISTS ONLY public.cliente DROP CONSTRAINT IF EXISTS fk_cliente_ciudad;
ALTER TABLE IF EXISTS ONLY public.ciudad DROP CONSTRAINT IF EXISTS fk_ciudad_departamento;
ALTER TABLE IF EXISTS ONLY public.tipo_identificacion DROP CONSTRAINT IF EXISTS uk_tipo_identificacion_codigo;
ALTER TABLE IF EXISTS ONLY public.pais DROP CONSTRAINT IF EXISTS uk_pais_nombre;
ALTER TABLE IF EXISTS ONLY public.marca DROP CONSTRAINT IF EXISTS uk_marca_nombre;
ALTER TABLE IF EXISTS ONLY public.departamento DROP CONSTRAINT IF EXISTS uk_departamento_nombre_pais;
ALTER TABLE IF EXISTS ONLY public.cliente DROP CONSTRAINT IF EXISTS uk_cliente_identificacion_marca;
ALTER TABLE IF EXISTS ONLY public.ciudad DROP CONSTRAINT IF EXISTS uk_ciudad_nombre_departamento;
ALTER TABLE IF EXISTS ONLY public.tipo_identificacion DROP CONSTRAINT IF EXISTS tipo_identificacion_pkey;
ALTER TABLE IF EXISTS ONLY public.pais DROP CONSTRAINT IF EXISTS pais_pkey;
ALTER TABLE IF EXISTS ONLY public.marca DROP CONSTRAINT IF EXISTS marca_pkey;
ALTER TABLE IF EXISTS ONLY public.departamento DROP CONSTRAINT IF EXISTS departamento_pkey;
ALTER TABLE IF EXISTS ONLY public.cliente DROP CONSTRAINT IF EXISTS cliente_pkey;
ALTER TABLE IF EXISTS ONLY public.ciudad DROP CONSTRAINT IF EXISTS ciudad_pkey;
DROP TABLE IF EXISTS public.tipo_identificacion;
DROP TABLE IF EXISTS public.pais;
DROP TABLE IF EXISTS public.marca;
DROP TABLE IF EXISTS public.departamento;
DROP TABLE IF EXISTS public.cliente;
DROP TABLE IF EXISTS public.ciudad;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ciudad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ciudad (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    departamento_id bigint NOT NULL
);


--
-- Name: ciudad_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ciudad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ciudad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cliente (
    id bigint NOT NULL,
    apellidos character varying(100) NOT NULL,
    direccion character varying(200) NOT NULL,
    fecha_nacimiento date NOT NULL,
    fecha_registro timestamp(6) without time zone NOT NULL,
    nombres character varying(100) NOT NULL,
    numero_identificacion character varying(20) NOT NULL,
    ciudad_id bigint NOT NULL,
    marca_id bigint NOT NULL,
    tipo_identificacion_id bigint NOT NULL
);


--
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departamento (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    pais_id bigint NOT NULL
);


--
-- Name: departamento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marca; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marca (
    id bigint NOT NULL,
    nombre character varying(60) NOT NULL
);


--
-- Name: marca_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.marca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pais; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pais (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: pais_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pais ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pais_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_identificacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipo_identificacion (
    id bigint NOT NULL,
    codigo character varying(5) NOT NULL,
    nombre character varying(60) NOT NULL
);


--
-- Name: tipo_identificacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tipo_identificacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_identificacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ciudad; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.ciudad (id, nombre, departamento_id) FROM stdin;
1	Leticia	1
2	Medellín	2
3	Arauca	3
4	Barranquilla	4
5	Cartagena	5
6	Tunja	6
7	Manizales	7
8	Florencia	8
9	Yopal	9
10	Popayán	10
11	Valledupar	11
12	Quibdó	12
13	Montería	13
14	Bogotá D.C.	14
15	Inírida	15
16	San José del Guaviare	16
17	Neiva	17
18	Riohacha	18
19	Santa Marta	19
20	Villavicencio	20
21	Pasto	21
22	Cúcuta	22
23	Mocoa	23
24	Armenia	24
25	Pereira	25
26	San Andrés	26
27	Bucaramanga	27
28	Sincelejo	28
29	Ibagué	29
30	Cali	30
31	Mitú	31
32	Puerto Carreño	32
33	Bello	2
34	Itagüí	2
35	Envigado	2
36	Rionegro	2
37	Apartadó	2
38	Turbo	2
39	Palmira	30
40	Buenaventura	30
41	Tuluá	30
42	Cartago	30
43	Buga	30
44	Jamundí	30
45	Soacha	14
46	Zipaquirá	14
47	Facatativá	14
48	Chía	14
49	Fusagasugá	14
50	Girardot	14
51	Soledad	4
52	Malambo	4
53	Sabanalarga	4
54	Floridablanca	27
55	Girón	27
56	Piedecuesta	27
57	Barrancabermeja	27
58	Magangué	5
59	Turbaco	5
60	Ocaña	22
61	Villa del Rosario	22
62	Los Patios	22
63	Espinal	29
64	Melgar	29
65	Ipiales	21
66	Tumaco	21
67	Lorica	13
68	Sahagún	13
69	La Dorada	7
70	Chinchiná	7
71	Dosquebradas	25
72	Santa Rosa de Cabal	25
73	Pitalito	17
74	Garzón	17
75	Acacías	20
76	Granada	20
\.


--
-- Data for Name: departamento; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.departamento (id, nombre, pais_id) FROM stdin;
1	Amazonas	1
2	Antioquia	1
3	Arauca	1
4	Atlántico	1
5	Bolívar	1
6	Boyacá	1
7	Caldas	1
8	Caquetá	1
9	Casanare	1
10	Cauca	1
11	Cesar	1
12	Chocó	1
13	Córdoba	1
14	Cundinamarca	1
15	Guainía	1
16	Guaviare	1
17	Huila	1
18	La Guajira	1
19	Magdalena	1
20	Meta	1
21	Nariño	1
22	Norte de Santander	1
23	Putumayo	1
24	Quindío	1
25	Risaralda	1
26	San Andrés y Providencia	1
27	Santander	1
28	Sucre	1
29	Tolima	1
30	Valle del Cauca	1
31	Vaupés	1
32	Vichada	1
\.


--
-- Data for Name: marca; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.marca (id, nombre) FROM stdin;
1	Americanino
2	American Eagle
3	Chevignon
4	Esprit
5	Naf Naf
6	Rifle
\.


--
-- Data for Name: pais; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pais (id, nombre) FROM stdin;
1	Colombia
\.


--
-- Data for Name: tipo_identificacion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tipo_identificacion (id, codigo, nombre) FROM stdin;
1	CC	Cédula de Ciudadanía
2	CE	Cédula de Extranjería
3	TI	Tarjeta de Identidad
4	PA	Pasaporte
5	NIT	Número de Identificación Tributaria
\.


--
-- Name: ciudad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ciudad_id_seq', 76, true);


--
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cliente_id_seq', 12, true);


--
-- Name: departamento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.departamento_id_seq', 32, true);


--
-- Name: marca_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.marca_id_seq', 6, true);


--
-- Name: pais_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pais_id_seq', 1, true);


--
-- Name: tipo_identificacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tipo_identificacion_id_seq', 5, true);


--
-- Name: ciudad ciudad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ciudad
    ADD CONSTRAINT ciudad_pkey PRIMARY KEY (id);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- Name: departamento departamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departamento
    ADD CONSTRAINT departamento_pkey PRIMARY KEY (id);


--
-- Name: marca marca_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT marca_pkey PRIMARY KEY (id);


--
-- Name: pais pais_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pais
    ADD CONSTRAINT pais_pkey PRIMARY KEY (id);


--
-- Name: tipo_identificacion tipo_identificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipo_identificacion
    ADD CONSTRAINT tipo_identificacion_pkey PRIMARY KEY (id);


--
-- Name: ciudad uk_ciudad_nombre_departamento; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ciudad
    ADD CONSTRAINT uk_ciudad_nombre_departamento UNIQUE (nombre, departamento_id);


--
-- Name: cliente uk_cliente_identificacion_marca; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT uk_cliente_identificacion_marca UNIQUE (tipo_identificacion_id, numero_identificacion, marca_id);


--
-- Name: departamento uk_departamento_nombre_pais; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departamento
    ADD CONSTRAINT uk_departamento_nombre_pais UNIQUE (nombre, pais_id);


--
-- Name: marca uk_marca_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT uk_marca_nombre UNIQUE (nombre);


--
-- Name: pais uk_pais_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pais
    ADD CONSTRAINT uk_pais_nombre UNIQUE (nombre);


--
-- Name: tipo_identificacion uk_tipo_identificacion_codigo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipo_identificacion
    ADD CONSTRAINT uk_tipo_identificacion_codigo UNIQUE (codigo);


--
-- Name: ciudad fk_ciudad_departamento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ciudad
    ADD CONSTRAINT fk_ciudad_departamento FOREIGN KEY (departamento_id) REFERENCES public.departamento(id);


--
-- Name: cliente fk_cliente_ciudad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT fk_cliente_ciudad FOREIGN KEY (ciudad_id) REFERENCES public.ciudad(id);


--
-- Name: cliente fk_cliente_marca; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT fk_cliente_marca FOREIGN KEY (marca_id) REFERENCES public.marca(id);


--
-- Name: cliente fk_cliente_tipo_identificacion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT fk_cliente_tipo_identificacion FOREIGN KEY (tipo_identificacion_id) REFERENCES public.tipo_identificacion(id);


--
-- Name: departamento fk_departamento_pais; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departamento
    ADD CONSTRAINT fk_departamento_pais FOREIGN KEY (pais_id) REFERENCES public.pais(id);


--
-- PostgreSQL database dump complete
--


